name: build
on:
  push:
    branches: [ feature/**, develop ]
jobs:
  build-lin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: My second step
      uses: IT-Medved/setup-onec-build-env-action@develop
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
