name: Тестирование
on:
  push:
    branches: 
      - feature/**
      - develop

  pull_request_target:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}-main
  cancel-in-progress: true

permissions:
    contents: write
    checks: write
    id-token: write

jobs:
  export_to_designer:
    name: Конвертация в формат конфигуратора
    uses: ./.github/workflows/step-export-xml.yml
    with:
      edt_version: 2023.1.2
      artifact_name: designer-src
    secrets: inherit
  
  build_artifacts:
    name: Сборка артифактов
    uses: ./.github/workflows/step-build-artifacts-windows.yml
    needs: export_to_designer
    with:
      v8_version: 8.3.21.1895
    secrets: inherit

  tests_windows:
    name: Тестирование в Windows
    strategy:
      fail-fast: false
      matrix:
        v8_version:
          - 8.3.21.1895
        locale:
          - ru_RU
          - en_US
    uses: ./.github/workflows/step-run-tests-windows.yml
    needs: build_artifacts
    with:
      v8_version: ${{ matrix.v8_version }}
      locale: ${{ matrix.locale }}
    secrets: inherit

  tests_linux:
    name: Тестирование в Linux
    strategy:
      fail-fast: false
      matrix:
        v8_version:
          - 8.3.21.1895
        locale:
          - ru_RU
          - en_US
    uses: ./.github/workflows/step-run-tests-linux.yml
    needs: build_artifacts
    with:
      v8_version: ${{ matrix.v8_version }}
      locale: ${{ matrix.locale }}
    secrets: inherit
