name: Run tests on Windows

on:
  workflow_call:
    inputs:
      v8_version:
        description: 'Platform version'
        type: string
        required: true

      locale:
        type: string
        required: false
        default: ru_RU

      artifact_name:
        type: string
        required: true
        
      fail_on_failure:
        type: boolean
        required: false
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.v8_version }}-${{ inputs.locale }}-Windows
  cancel-in-progress: true

jobs:
  execute-tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:

    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: binary

    - name: install platform
      uses: alkoleft/onec-setup-build-env-action@develop
      with:
        type: onec
        onec_version: ${{ inputs.v8_version }}
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 10

    - name: prepare
      run: mkdir data\data
      
    - name: create IB
      run: ibcmd.exe infobase create --data=data --load=binary\configuration.cf --apply --force
      timeout-minutes: 5

    - name: load yaxunit
      run: |
        ibcmd.exe infobase config load --data=data --extension=YAXUNIT --force binary\yaxunit.cfe
        ibcmd.exe infobase config apply --data=data --extension=YAXUNIT --force
        ibcmd.exe infobase config extension update --data=data --name=YAXUNIT --safe-mode=no --unsafe-action-protection=no
      timeout-minutes: 5

    - name: load tests
      run: |
        ibcmd.exe infobase config load --data=data --extension=tests --force binary\tests.cfe
        ibcmd.exe infobase config apply --data=data --extension=tests --force
        ibcmd.exe infobase config extension update --data=data --name=tests --safe-mode=no --unsafe-action-protection=no
      timeout-minutes: 5

    - uses: JarvusInnovations/background-action@v1
      name: run server
      with:
        run: Start-Process -NoNewWindow ibsrv.exe --data=data
        wait-on: |
          http://localhost:8314
   
    - name: create test-config
      uses: DamianReeves/write-file-action@master
      with:
        path: unit.json
        contents: |
          {
            "reportFormat": "jUnit",
            "reportPath": "reports\\report.xml",
            "closeAfterTests": true,
            "exitCode": "exit-code.txt",
            "logging": {
              "console": true
            }
          }
    
    - name: server answer
      shell: pwsh
      run: curl http://localhost:8314
    
    - name: run tests
      run: 1cv8c.exe /WS "http://localhost:8314" /C"RunUnitTests=unit.json" /DisableStartupDialogs /DisableStartupMessages /DisableUnrecoverableErrorMessage /Out output.log
      timeout-minutes: 5
      env:
        LANG: "${{ inputs.locale }}.UTF-8"
      
    - name: server answer2
      shell: pwsh
      run: curl http://localhost:8314
    
    - name: view output
      if: always()
      run: type output.log
    
    - name: upload-artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Tests report. Windows ${{ inputs.v8_version }} ${{ inputs.locale }}
        path: reports\*.*
        
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        job_name: Tests Windows ${{ inputs.v8_version }} ${{ inputs.locale }}
        check_name: Tests report. Windows ${{ inputs.v8_version }} ${{ inputs.locale }}
        report_paths: reports\report.xml
        fail_on_failure: ${{ inputs.fail_on_failure }}
        require_passed_tests: true
